# Generated by Django 4.2.10 on 2025-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Auther',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
