# Generated by Django 4.2.10 on 2025-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='apply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
